//
//  DefaultDevOpsGlossary.swift
//  GrammarPolice
//
//  Built-in terms the LLM must not "correct" (PR != public relations).
//  Merged at mask time; not written into the user's custom_words.json.
//

import Foundation

enum DefaultDevOpsGlossary {
    static let terms: [String] = [
        "PR",
        "PRs",
        "LGTM",
        "WIP",
        "RFC",
        "CI",
        "CD",
        "CI/CD",
        "CDKs",
        "CDK",
        "k8s",
        "kubectl",
        "kubelet",
        "kube-system",
        "namespace",
        "namespaces",
        "rollout",
        "rollouts",
        "ArgoCD",
        "Argo",
        "Helm",
        "helm",
        "VPA",
        "HPA",
        "HPA/VPA",
        "PDB",
        "CRD",
        "CRDs",
        "Ingress",
        "ServiceAccount",
        "ConfigMap",
        "Secret",
        "StatefulSet",
        "DaemonSet",
        "ReplicaSet",
        "Deployment",
        "Job",
        "CronJob",
        "Pod",
        "nodepool",
        "node pool",
        "runner pool",
        "AutoPilot",
        "autopilot",
        "Terraform",
        "Pulumi",
        "Ansible",
        "Ollama",
        "DevOps",
        "SRE",
        "SLO",
        "SLI",
        "SLA",
        "PagerDuty",
        "Jira",
        "Slack",
        "GitHub",
        "GitLab",
        "Bitbucket",
        "gRPC",
        "REST",
        "OpenAPI",
        "JSON",
        "YAML",
        "IAM",
        "OIDC",
        "OAuth",
        "SSO",
        "VPN",
        "VPC",
        "EKS",
        "GKE",
        "AKS",
        "EC2",
        "S3",
        "RDS",
        "SQS",
        "SNS",
        "Lambda",
        "CloudWatch",
        "Datadog",
        "Prometheus",
        "Grafana",
        "Loki",
        "Tempo",
        "Istio",
        "Linkerd",
        "Traefik",
        "nginx",
        "Envoy",
        "Redis",
        "Postgres",
        "PostgreSQL",
        "MySQL",
        "Kafka",
        "Temporal",
        "Airflow",
        "Spark",
        "Flink",
        "kubectl apply",
        "helm upgrade",
        "helm install",
        "git rebase",
        "git cherry-pick",
        "canary",
        "blue-green",
        "feature flag",
        "feature flags",
        "hotfix",
        "rollback",
        "runbook",
        "on-call",
        "oncall",
        "prod",
        "staging",
        "devhub",
        "k8s-deploy"
    ]

    static func words() -> [CustomWord] {
        terms.map { term in
            CustomWord(
                word: term,
                caseSensitive: false,
                wholeWordMatch: true
            )
        }
    }
}
